"""create ml_accounts table

Revision ID: 6f85e4bbc16f
Revises: 99affaceb83a
Create Date: 2026-07-21 09:55:41.666820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f85e4bbc16f'
down_revision: Union[str, Sequence[str], None] = '99affaceb83a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ml_user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=120), nullable=False),
    sa.Column('site_id', sa.String(length=10), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_type', sa.String(length=30), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_accounts_is_active'), 'ml_accounts', ['is_active'], unique=False)
    op.create_index(op.f('ix_ml_accounts_ml_user_id'), 'ml_accounts', ['ml_user_id'], unique=True)
    op.create_index(op.f('ix_ml_accounts_nickname'), 'ml_accounts', ['nickname'], unique=False)
    op.create_index(op.f('ix_ml_accounts_user_id'), 'ml_accounts', ['user_id'], unique=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=320),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_ml_accounts_user_id'), table_name='ml_accounts')
    op.drop_index(op.f('ix_ml_accounts_nickname'), table_name='ml_accounts')
    op.drop_index(op.f('ix_ml_accounts_ml_user_id'), table_name='ml_accounts')
    op.drop_index(op.f('ix_ml_accounts_is_active'), table_name='ml_accounts')
    op.drop_table('ml_accounts')
    # ### end Alembic commands ###
